# WhatATheme
markdown: kramdown

# URL of the Site
url:
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Emiel Lemahieu
# Description of the Site
description: Quantitative Researcher
# URL of Image of the Site
site-image: ./assets/images/craiyon_210001_A_signature_stock_trading_algorithm_with_blood_red_colours_and_wine_red_colours.png
# Keywords of the Site
site-keywords: Emiel, Lemahieu, Researcher, Machine Learning, Finance
# URL for the Image of custom Favicon
favicon-url: ./assets/images/craiyon_210001_A_signature_stock_trading_algorithm_with_blood_red_colours_and_wine_red_colours.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage_desktop: "../images/new-york-arno.png" # "https://media3.giphy.com/media/dee1Gnqb84oJFst30V/giphy.gif?cid=790b7611fe9a07f98b9444694bb17a74fb6c320ae8a60db3&rid=giphy.gif&ct=g"
heroimage_mobile:  "https://media.giphy.com/media/Ha6xdymclg2pBgwuw3/giphy.gif"

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: emiel.lemahieu@investsuite.com
facebook_username: 
twitter_username: 
instagram_username:
linkedin_username: emiellemahieu
github_username:  emiellemahieu
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: G-291QW7VCC2

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Emiel Lemahieu
# URL for the Image of the Author
author-image: ./assets/images/cv_pic.png
# 60 Words About the Author
author-about: "Quant Researcher"
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://linkedin.com/in/emiel-lemahieu

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
