# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Emiel Lemahieu
# Description of the Site
description: Quantitative Researcher
# URL of Image of the Site
site-image: ./assets/images/NY-Short-2.gif
# Keywords of the Site
site-keywords: Emiel, Lemahieu, Researcher, Machine Learning, Finance
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: ./assets/images/Highway.gif
heroimage: https://thumbs.gfycat.com/EarlyImpartialAlpaca-mobile.mp4

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: emiel.lemahieu@investsuite.com
facebook_username: 
twitter_username: 
instagram_username:
linkedin_username: emiellemahieu
github_username:  emiellemahieu
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: G-291QW7VCC2

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Emiel Lemahieu
# URL for the Image of the Author
author-image: ./assets/images/cv_pic.png
# 60 Words About the Author
author-about: "**Emiel Lemahieu** is a quantitative researcher at the Belgian robo-advisory **InvestSuite** and **Ghent University**. His research focuses on **data-driven portfolio construction** techniques. Starting from the general aim to offer smooth-ride investments to retail investors through robo-advisory tools, Emiel has explored traditional risk-based optimization techniques and ways to improve them using novel machine learning approaches. In particular, his research interests lie in using generative machine learning techniques for simulating optimal drawdown portfolios and graph-based methods to assess common sources of downside risk. Emiel holds an **MSc Finance** from **Ghent University** and **King's College London** and is currently pursuing his **PhD at Ghent University**."
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://linkedin.com/in/emiel-lemahieu

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
